# -*- coding: utf-8 -*-
"""DO_PartB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cG-xdrEQSp7zUyRA5KfVkN4OAxusfe8-
"""

!pip install --upgrade --force-reinstall ecos

!pip freeze | grep ecos

import cvxpy as cp
print("Installed solvers:", cp.installed_solvers())

"""Question 1 b)"""

import numpy as np
import cvxpy as cp
import csv
e_demand = np.genfromtxt("6669_Project_Electricity_Demand.csv", delimiter=',', skip_header=1)[:72, 1]
e_prices = np.genfromtxt("6669_Project_Electricity_Prices.csv", delimiter=',', skip_header=1)[:72, 2]
h_demand = np.genfromtxt("6669_Project_Hydrogen_Demand.csv", delimiter=',', skip_header=1)[:72, 1]
solar_forecast = np.genfromtxt("6669_Project_Solar_Forecast.csv", delimiter=',', skip_header=1)[:72, 1]

# Constants
num_hours = 72
solar_capacity = 2  # MW
electrolyser_power = 0.5  # MWh/hour
electrolyser_output = 9  # kg hydrogen/hour
hydrogen_price = 10  # $/kg

# Adjusted electricity demand (after solar generation)
solar_generation = solar_forecast * solar_capacity
adjusted_e_demand = np.maximum(e_demand - solar_generation, 0)

# Decision variables
E = cp.Variable(num_hours)                    # Electricity purchased
H = cp.Variable(num_hours)                    # Hydrogen purchased
Y = cp.Variable(num_hours, boolean=True)      # Electrolyser ON/OFF
H_stock = cp.Variable(num_hours + 1)          # Hydrogen stock over time

# Constraints
constraints = [H_stock[0] == 0]

for t in range(num_hours):
    # Electricity constraint
    constraints.append(E[t] >= adjusted_e_demand[t] + electrolyser_power * Y[t])

    # Hydrogen availability constraint
    constraints.append(H[t] + electrolyser_output * Y[t] + H_stock[t] >= h_demand[t])

    # Hydrogen storage update
    constraints.append(H_stock[t+1] == H[t] + electrolyser_output * Y[t] + H_stock[t] - h_demand[t])

    # Non-negativity
    constraints.append(E[t] >= 0)
    constraints.append(H[t] >= 0)
    constraints.append(H_stock[t+1] >= 0)

# Objective function
objective = cp.Minimize(cp.sum(H) * hydrogen_price + e_prices @ E)

# Solve
problem = cp.Problem(objective, constraints)
problem.solve()

# Print results
print("Solver status:", problem.status)
print("Total operational cost with electrolyser: ${:,.2f}".format(problem.value))

# Save electrolyser use to CSV
with open("Electrolyser_Use.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["Hour", "ElectrolyserOn"])
    for t in range(num_hours):
        writer.writerow([t, int(round(Y[t].value))])

Question 2 a)

import numpy as np
import cvxpy as cp
e_demand = np.genfromtxt("6669_Project_Electricity_Demand.csv", delimiter=',', skip_header=1)[:72, 1]
e_prices = np.genfromtxt("6669_Project_Electricity_Prices.csv", delimiter=',', skip_header=1)[:72, 2]
h_demand = np.genfromtxt("6669_Project_Hydrogen_Demand.csv", delimiter=',', skip_header=1)[:72, 1]
solar_forecast = np.genfromtxt("6669_Project_Solar_Forecast.csv", delimiter=',', skip_header=1)[:72, 1]

num_hours = 72
solar_capacity = 2.0 + 0.4  # 2.4 MW
solar_generation = solar_forecast * solar_capacity  # Hourly solar generation (MWh)
E = cp.Variable(num_hours, nonneg=True)
H = cp.Variable(num_hours, nonneg=True)

#constraints
constraints = []
for t in range(num_hours):
    constraints.append(E[t] + solar_generation[t] >= e_demand[t])
    constraints.append(H[t] >= h_demand[t])
objective = cp.Minimize(e_prices @ E + 10 * cp.sum(H))
problem_q1 = cp.Problem(objective, constraints)
problem_q1.solve(solver=cp.SCS)

print("Solver status:", problem_q1.status)
print("Optimal operational cost with 2.4 MW solar capacity: ${:,.2f}".format(problem_q1.value))

"""b)"""

!pip install --upgrade --force-reinstall numpy

!pip freeze | grep -E 'numpy|cylp|cvxpy'

!pip uninstall -y numpy
!pip install --no-cache-dir "numpy==1.23.5"

!apt-get install -y coinor-cbc

!apt-get update
!apt-get install -y coinor-cbc

"""Question 2 b)"""

!pip install cylp
import numpy as np
import cvxpy as cp

e_demand = np.genfromtxt("6669_Project_Electricity_Demand.csv", delimiter=',', skip_header=1)[:72, 1]
e_prices = np.genfromtxt("6669_Project_Electricity_Prices.csv", delimiter=',', skip_header=1)[:72, 2]
h_demand = np.genfromtxt("6669_Project_Hydrogen_Demand.csv", delimiter=',', skip_header=1)[:72, 1]
solar_forecast = np.genfromtxt("6669_Project_Solar_Forecast.csv", delimiter=',', skip_header=1)[:72, 1]

num_hours = 72

# Parameters
base_solar_capacity = 2.0
block_capacity = 0.2
panel_cost = 900000.0
amort_period = 3.5 * 365 * 24
amort_factor = num_hours / amort_period


E = cp.Variable(num_hours, nonneg=True)
H = cp.Variable(num_hours, nonneg=True)
S = cp.Variable(integer=True)

# Constraints
constraints = []
constraints.append(S >= 0)
for t in range(num_hours):
    constraints.append(
        E[t] + (base_solar_capacity + block_capacity * S) * solar_forecast[t] >= e_demand[t]
    )
    constraints.append(H[t] >= h_demand[t])

grid_cost = e_prices @ E
hydrogen_cost = 10 * cp.sum(H)
solar_cost = panel_cost * amort_factor * S
objective = cp.Minimize(grid_cost + hydrogen_cost + solar_cost)

problem_q2 = cp.Problem(objective, constraints)
problem_q2.solve(solver=cp.CBC)

print("Solver status:", problem_q2.status)
print("Optimal operational cost over 72 hours: ${:,.2f}".format(problem_q2.value))
S_opt = S.value if S.value is not None else 0
print("Optimal number of extra 0.2 MW solar blocks (S):", int(round(S_opt)))

"""Question 3"""

# Parameters
N = 72
P_H = 10  # $/kg
solar_capacity = 2  # MW
solar_generation = solar_forecast * solar_capacity
battery_capacity = 0.5  # MWh

# Decision variables
E = cp.Variable(N)  # Electricity purchased
H = cp.Variable(N)  # Hydrogen purchased
B_in = cp.Variable(N)  # Battery charging
B_out = cp.Variable(N)  # Battery discharging
B_level = cp.Variable(N+1)  # Battery state of charge

# Objective
objective = cp.Minimize(cp.sum(cp.multiply(e_prices, E) + P_H * H))

# Constraints
constraints = [
    E + solar_generation + B_out >= e_demand + B_in,
    B_level[0] == 0,
    B_level[1:] == B_level[:-1] + B_in - B_out,
    B_in <= battery_capacity,
    B_out <= battery_capacity,
    B_level <= battery_capacity,
    cp.cumsum(H) >= cp.cumsum(h_demand),
    E >= 0,
    H >= 0,
    B_in >= 0,
    B_out >= 0
]

# Solve
problem_q3 = cp.Problem(objective, constraints)
problem_q3.solve(solver=cp.CBC)

print(f"Optimal cost with battery: ${problem_q3.value:.2f}")

"""Question 4"""

# === Q4: Payback Periods ===

original_cost = 44409.00  # From baseline with no components

# From previous optimization problems
cost_q1 = problem.value  # From electrolyser model
cost_q2 = 44_342.06 # From optimized solar
cost_q3 = problem_q3.value  # From battery model

electrolyser_capex = 500000
battery_capex = 75000
solar_block_capex = 900000  # per 0.2 MW block
num_solar_blocks = 10       # Assume 2 MW added = 10 blocks
total_solar_capex = solar_block_capex * num_solar_blocks

# Scale savings to annual values (3-day simulation → 365 days)
scaling_factor = 365 / 3
electrolyser_savings = (original_cost - cost_q1) * scaling_factor
solar_savings = (original_cost - cost_q2) * scaling_factor
battery_savings = (original_cost - cost_q3) * scaling_factor

# Payback periods (years)
electrolyser_payback = electrolyser_capex / electrolyser_savings
solar_payback = total_solar_capex / solar_savings
battery_payback = battery_capex / battery_savings

print(f"Electrolyser payback: {electrolyser_payback:.1f} years")
print(f"Solar payback: {solar_payback:.1f} years")
print(f"Battery payback: {battery_payback:.1f} years")

# Recommendation
best = min([
    ("Electrolyser", electrolyser_payback),
    ("Solar", solar_payback),
    ("Battery", battery_payback)
], key=lambda x: x[1])

print(f"\nQ4 Recommendation: Invest in {best[0]} (Payback: {best[1]:.1f} years)")